variables:
  url: http://www.abcd.com/
  loginDastConfig: $CI_PROJECT_DIR\dast.login
  manualExploreDastConfig: $CI_PROJECT_DIR\manualexplore.exd
  aseHostname: xxxxxxxxxxxxxxxxxxxx
  aseApiKeyId: xxxxxxxxxxxxxxxxxxxx
  aseApiKeySecret: xxxxxxxxxxxxxxxxxxxx
  aseAppName: $CI_PROJECT_NAME
  sevSecGw: highIssues
  maxIssuesAllowed: 10
  scanTemplate: xxx

stages:
  - scan-dast

scan-dast-job:
  stage: scan-dast
  script:

    - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscanase_create_application_ase.ps1 -OutFile appscanase_create_application_ase.ps1
    - .\appscanase_create_application_ase.ps1

    - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscanase_scan.ps1 -OutFile appscanase_scan.ps1
    - .\appscanase_scan.ps1

    - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscanase_get_pdf_report_from_enterprise.ps1 -OutFile appscanase_get_pdf_report_from_enterprise.ps1
    - .\appscanase_get_pdf_report_from_enterprise.ps1

    - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscanase_get_xml_report_from_enterprise.ps1 -OutFile appscanase_get_xml_report_from_enterprise.ps1
    - .\appscanase_get_xml_report_from_enterprise.ps1

    - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscanase_convert_ase_dast_xml_to_gitlab_json.ps1 -OutFile appscanase_convert_ase_dast_xml_to_gitlab_json.ps1
    - .\appscanase_convert_ase_dast_xml_to_gitlab_json.ps1

    - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscanase_check_security_gate.ps1 -OutFile appscanase_check_security_gate.ps1
    - .\appscanase_check_security_gate.ps1

  artifacts:
    when: always
    reports:
      dast: .\scan_report\gl-dast-report.json
    paths:
      - "*.pdf"
