variables:
  aseToken: C:\ProgramData\HCL\AppScanSource\config\ounceautod.token
  artifactFolder: $CI_PROJECT_DIR\build\libs 
  artifactName: xxxxxxxxxxxx.war
# compiledArtifactFolder: none
  sevSecGw: highIssues
  maxIssuesAllowed: 80

stages:
- scan

scan-job:
  stage: scan
  script:
  - write-host "======== Step 1 - Building artifact ========"
  - gradle build

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscansrc_create_config_scan_file.ps1 -OutFile appscansrc_create_config_scan_file.ps1
  - .\appscansrc_create_config_scan_file.ps1

  # new! You can read the folder using Open Folder (OF) AppScan parameter
  #- Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscansrc_create_config_scan_folder.ps1 -OutFile appscansrc_create_config_scan_folder.ps1
  #- .\appscansrc_create_config_scan_folder.ps1

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscansrc_scan.ps1 -OutFile appscansrc_scan.ps1
  - .\appscansrc_scan.ps1

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscansrc_check_security_gate.ps1 -OutFile appscansrc_check_security_gate.ps1
  - .\appscansrc_check_security_gate.ps1

  artifacts:
    when: always
    paths:
      - "*.ozasmt"
      - "*.pdf"
