variables:
  aseToken: C:\ProgramData\HCL\AppScanSource\config\ounceautod.token
  aseHostname: xxxxxxxxxxxx
  aseAppName: $CI_PROJECT_NAME
  aseApiKeyId: xxxxxxxxxxxx
  aseApiKeySecret: xxxxxxxxxxxx
  artifactFolder: $CI_PROJECT_DIR\build\libs 
  artifactName: xxxxxxxxxxxx.war
  sevSecGw: highIssues
  maxIssuesAllowed: 80

stages:
- scan

scan-job:
  stage: scan
  script:
  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscanase_create_application_ase.ps1 -OutFile appscanase_create_application_ase.ps1
  - .\appscanase_create_application_ase.ps1

  - write-host "======== Step: Building artifact ========"
  - gradle build

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscansrc_create_config_scan_file.ps1 -OutFile appscansrc_create_config_scan_file.ps1
  - .\appscansrc_create_config_scan_file.ps1

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscansrc_scan.ps1 -OutFile appscansrc_scan.ps1
  - .\appscansrc_scan.ps1

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscansrc_publish_assessment_to_enterprise.ps1 -OutFile appscansrc_publish_assessment_to_enterprise.ps1
  - .\appscansrc_publish_assessment_to_enterprise.ps1

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscanase_get_xml_report_from_enterprise.ps1 -OutFile appscanase_get_xml_report_from_enterprise.ps1
  - .\appscanase_get_xml_report_from_enterprise.ps1

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscanase_convert_ase_sast_xml_to_gitlab_json.ps1 -OutFile appscanase_convert_ase_sast_xml_to_gitlab_json.ps1
  - .\appscanase_convert_ase_sast_xml_to_gitlab_json.ps1

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscansrc_check_security_gate.ps1 -OutFile appscansrc_check_security_gate.ps1
  - .\appscansrc_check_security_gate.ps1

  artifacts:
    when: always
    paths:
      - "*.ozasmt"
      - "*.zip"
    reports:
      sast: .\scan_report\gl-sast-report.json
